
version: "3"
services:
  frontend:
    build: .
    image: frontend
    container_name: frontend
    build:
       context: .
    ports:
      - "8080:80"
    restart: on-failure
    networks:
       project222:
          ipv4_address: 172.25.0.5


networks:
  default:
    external:
       name: project222
  project222:
    external: true
